import React from 'react'

function PolicyCE() {
  return (
    <>

      {/* Large Screen UI */}
      <div className='lg:block md:hidden hidden'>

        <div className='lg:block'>
          <h2 className='lg:font-semibold lg:text-center lg:text-6xl'>Privacy Policy</h2>
          <p className='lg:px-8 lg:pt-16 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>
            This Privacy Policy (the “Policy”) describes how Chowdhury Enterprises, collects, uses, shares and protects personal information that we collect from you, the end user of the Chowdhury Enterprises website and services (collectively, “Chowdhury Enterprises Products”).
          </p>
          <p className='lg:px-8 lg:pt-8 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>
            While you use and enjoy our services, we want to keep you informed about our privacy policy towards management and security of your personal information. We value the trust you place in us, and hence insist upon the highest level of protection for securing your personal information. We are obligated to protect your personal information in accordance with applicable laws, and regulations.
          </p>
          <p className='lg:px-8 lg:pt-8 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>
            This Privacy Policy is an electronic record in terms of the Information Technology Act, 2000 (as amended/re-enacted from time to time) (“IT Act') and rules thereunder, and, amongst others, is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021, which mandates for publishing of rules and regulations, privacy policy and terms of use for access or usage of the App. This Privacy Policy is an electronic record, generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className='lg:px-8 lg:pt-8 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>
            This Policy should be read in conjunction with Terms and Conditions. Registration or usage of any of Chowdhury Enterprises services implies your express consent and agreement to this Policy.
          </p>
          <p className='lg:px-8 lg:py-8 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>
            This Policy is subject to modification based on changes in the business, legal and regulatory requirements and will be made available to you online. We will make all efforts to communicate about significant changes to this policy. You are encouraged to periodically visit this page to review the policy and any changes.
          </p>
        </div>

        {/* <hr className='py-8 w-3/4 block h-8 m-8 mx-auto font-bold text-green-700' /> */}

        <div class='lg:inline-flex lg:items-center lg:justify-center lg:w-full'>
          <hr class='lg:w-2/3 lg:h-px lg:my-8 lg:border-0 lg:bg-black' />
          <span class='lg:absolute lg:px-3 lg:font-medium lg:-translate-x-1/2 lg:left-1/2 lg:text-black lg:bg-black'>...</span>
        </div>

        <div className='lg:block'>
          <h2 className='lg:font-semibold lg:text-center lg:text-6xl'>Privacy Policy</h2>
          <p className='lg:px-8 lg:pt-8 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>
            In order to enable us in providing you with the best in class services, we require certain information be shared by you with us. Chowdhury Enterprises may collect the following types of information:
            “Personal Information” which shall mean information which could reasonably be used to identify you personally, which may include, but not limited to the following:
          </p>
          {/* <p className='px-8 py-8 w-2/3 mx-auto text-lg text-center tracking-wide'> */}
          <ul className='lg:list-disc lg:text-left lg:px-8 lg:pt-8 lg:w-7/12 lg:mx-auto lg:text-lg lg:tracking-wide'>
            <li>Basic details which you provide during the registration process such as Name, Phone Number, Email Address, Communication or Permanent Address.</li>
            <li>Photograph provided during registration or during the profile update.</li>
            <li>Proof of Identity and Address documents such as PAN Card, Driving License, Passport etc.</li>
            <li>Transactions performed which can identify you as an individual through your customer ID or other relevant unique identifier.</li>
            <li>Demographic details such as gender, city, PIN code or nearest location.</li>
            <li>Usage logs/Server logs/Cookies which may contain details of your personal or sensitive personal information.</li>
            <li>Service specific information or identifiers such as IMSI, MSISDN, Customer ID etc.</li>
            <li>Device specific information or identifiers such as IMEI, OS specific identifiers.</li>
            <li>For the purpose of this policy, sensitive personal data or information has been considered as a part of Personal Information, which may include, but not limited to the following:
              <ul>
                <li>Passwords or authentication information for any of our services or apps.</li>
                <li>Financial information, such as details of bank account, credit card, debit card, or other payment instrument details etc</li>
              </ul>
            </li>
          </ul>
          {/* </p> */}
          <p className='lg:px-8 lg:pt-8 lg:pb-16 lg:w-2/3 lg:mx-auto lg:text-lg lg:text-center lg:tracking-wide'>“Non-Personal Information” which shall mean information that does not identify you or any other individual, and includes session, web beacons and usage and transaction data, aggregate log data and aggregate information. We use this information to inter-alia deliver our web pages to you upon request, to tailor our services to the interests of our users, to measure traffic within our services, to improve the quality, functionality and interactivity and let advertisers know the geographic locations from where our users/ visitors come.</p>
        </div>
      </div>

      {/* Tablet Screen UI */}
      <div className='md:block lg:hidden hidden'>

        <div className='md:block'>
          <h2 className='md:pt-8 md:font-semibold md:text-center md:text-4xl'>Privacy Policy</h2>
          <p className='md:px-8 md:pt-16 md:w-2/3 md:mx-auto md:text-lg md:text-justify md:tracking-wide'>
            This Privacy Policy (the “Policy”) describes how Chowdhury Enterprises, collects, uses, shares and protects personal information that we collect from you, the end user of the Chowdhury Enterprises website and services (collectively, “Chowdhury Enterprises Products”).
          </p>
          <p className='md:px-8 md:pt-8 md:w-2/3 md:mx-auto md:text-lg md:text-justify md:tracking-wide'>
            While you use and enjoy our services, we want to keep you informed about our privacy policy towards management and security of your personal information. We value the trust you place in us, and hence insist upon the highest level of protection for securing your personal information. We are obligated to protect your personal information in accordance with applicable laws, and regulations.
          </p>
          <p className='md:px-8 md:pt-8 md:w-2/3 md:mx-auto md:text-lg md:text-justify md:tracking-wide'>
            This Privacy Policy is an electronic record in terms of the Information Technology Act, 2000 (as amended/re-enacted from time to time) (“IT Act') and rules thereunder, and, amongst others, is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021, which mandates for publishing of rules and regulations, privacy policy and terms of use for access or usage of the App. This Privacy Policy is an electronic record, generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className='md:px-8 md:pt-8 md:w-2/3 md:mx-auto md:text-lg md:text-justify md:tracking-wide'>
            This Policy should be read in conjunction with Terms and Conditions. Registration or usage of any of Chowdhury Enterprises services implies your express consent and agreement to this Policy.
          </p>
          <p className='md:px-8 md:py-8 md:w-2/3 md:mx-auto md:text-lg md:text-justify md:tracking-wide'>
            This Policy is subject to modification based on changes in the business, legal and regulatory requirements and will be made available to you online. We will make all efforts to communicate about significant changes to this policy. You are encouraged to periodically visit this page to review the policy and any changes.
          </p>
        </div>

        {/* <hr className='py-8 w-3/4 block h-8 m-8 mx-auto font-bold text-green-700' /> */}

        <div class='md:inline-flex md:items-center md:justify-center md:w-full'>
          <hr class='md:w-2/3 md:h-px md:my-8 md:border-0 md:bg-black' />
          <span class='md:absolute md:px-3 md:font-medium md:-translate-x-1/2 md:left-1/2 md:text-black md:bg-black'>...</span>
        </div>

        <div className='md:block'>
          <h2 className='md:font-semibold md:text-center md:text-4xl'>Privacy Policy</h2>
          <p className='md:px-8 md:pt-8 md:w-2/3 md:mx-auto md:text-lg md:justify md:tracking-wide'>
            In order to enable us in providing you with the best in class services, we require certain information be shared by you with us. Chowdhury Enterprises may collect the following types of information:
            “Personal Information” which shall mean information which could reasonably be used to identify you personally, which may include, but not limited to the following:
          </p>
          {/* <p className='px-8 py-8 w-2/3 mx-auto text-lg text-center tracking-wide'> */}
          <ul className='md:list-disc md:text-left md:px-8 md:pt-8 md:w-7/12 md:mx-auto md:text-lg md:tracking-wide'>
            <li>Basic details which you provide during the registration process such as Name, Phone Number, Email Address, Communication or Permanent Address.</li>
            <li>Photograph provided during registration or during the profile update.</li>
            <li>Proof of Identity and Address documents such as PAN Card, Driving License, Passport etc.</li>
            <li>Transactions performed which can identify you as an individual through your customer ID or other relevant unique identifier.</li>
            <li>Demographic details such as gender, city, PIN code or nearest location.</li>
            <li>Usage logs/Server logs/Cookies which may contain details of your personal or sensitive personal information.</li>
            <li>Service specific information or identifiers such as IMSI, MSISDN, Customer ID etc.</li>
            <li>Device specific information or identifiers such as IMEI, OS specific identifiers.</li>
            <li>For the purpose of this policy, sensitive personal data or information has been considered as a part of Personal Information, which may include, but not limited to the following:
              <ul>
                <li>Passwords or authentication information for any of our services or apps.</li>
                <li>Financial information, such as details of bank account, credit card, debit card, or other payment instrument details etc</li>
              </ul>
            </li>
          </ul>
          {/* </p> */}
          <p className='md:px-8 md:pt-8 md:pb-16 md:w-2/3 md:mx-auto md:text-lg md:text-justify md:tracking-wide'>“Non-Personal Information” which shall mean information that does not identify you or any other individual, and includes session, web beacons and usage and transaction data, aggregate log data and aggregate information. We use this information to inter-alia deliver our web pages to you upon request, to tailor our services to the interests of our users, to measure traffic within our services, to improve the quality, functionality and interactivity and let advertisers know the geographic locations from where our users/ visitors come.</p>
        </div>
      </div>

      {/* Mobile Screen UI */}
      <div className='block lg:hidden md:hidden'>

        <div className='block'>
          <h2 className='pt-8 font-semibold text-center text-3xl'>Privacy Policy</h2>
          <p className='px-8 pt-8 w-full mx-auto text-base text-justify tracking-wide'>
            This Privacy Policy (the “Policy”) describes how Chowdhury Enterprises, collects, uses, shares and protects personal information that we collect from you, the end user of the Chowdhury Enterprises website and services (collectively, “Chowdhury Enterprises Products”).
          </p>
          <p className='px-8 pt-4 w-full mx-auto text-base text-justify tracking-wide'>
            While you use and enjoy our services, we want to keep you informed about our privacy policy towards management and security of your personal information. We value the trust you place in us, and hence insist upon the highest level of protection for securing your personal information. We are obligated to protect your personal information in accordance with applicable laws, and regulations.
          </p>
          <p className='px-8 pt-4 w-full mx-auto text-base text-justify tracking-wide'>
            This Privacy Policy is an electronic record in terms of the Information Technology Act, 2000 (as amended/re-enacted from time to time) (“IT Act') and rules thereunder, and, amongst others, is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021, which mandates for publishing of rules and regulations, privacy policy and terms of use for access or usage of the App. This Privacy Policy is an electronic record, generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p className='px-8 pt-4 w-full mx-auto text-base text-justify tracking-wide'>
            This Policy should be read in conjunction with Terms and Conditions. Registration or usage of any of Chowdhury Enterprises services implies your express consent and agreement to this Policy.
          </p>
          <p className='px-8 pb-8 pt-4 w-full mx-auto text-base text-justify tracking-wide'>
            This Policy is subject to modification based on changes in the business, legal and regulatory requirements and will be made available to you online. We will make all efforts to communicate about significant changes to this policy. You are encouraged to periodically visit this page to review the policy and any changes.
          </p>
        </div>

        {/* <hr className='py-8 w-3/4 block h-8 m-8 mx-auto font-bold text-green-700' /> */}

        <div class='inline-flex items-center justify-center w-full'>
          <hr class='w-2/3 h-px my-8 border-0 bg-black' />
          <span class='absolute px-3 font-medium -translate-x-1/2 left-1/2 text-black bg-black'>...</span>
        </div>

        <div className='block'>
          <h2 className='font-semibold text-center text-3xl'>Privacy Policy</h2>
          <p className='px-8 pt-8 w-full mx-auto text-base text-justify tracking-wide'>
            In order to enable us in providing you with the best in class services, we require certain information be shared by you with us. Chowdhury Enterprises may collect the following types of information:
            “Personal Information” which shall mean information which could reasonably be used to identify you personally, which may include, but not limited to the following:
          </p>
          {/* <p className='px-8 py-8 w-2/3 mx-auto text-lg text-center tracking-wide'> */}
          <ul className='list-disc text-left px-2 pt-4 w-7/12 mx-auto text-base tracking-wide'>
            <li>Basic details which you provide during the registration process such as Name, Phone Number, Email Address, Communication or Permanent Address.</li>
            <li>Photograph provided during registration or during the profile update.</li>
            <li>Proof of Identity and Address documents such as PAN Card, Driving License, Passport etc.</li>
            <li>Transactions performed which can identify you as an individual through your customer ID or other relevant unique identifier.</li>
            <li>Demographic details such as gender, city, PIN code or nearest location.</li>
            <li>Usage logs/Server logs/Cookies which may contain details of your personal or sensitive personal information.</li>
            <li>Service specific information or identifiers such as IMSI, MSISDN, Customer ID etc.</li>
            <li>Device specific information or identifiers such as IMEI, OS specific identifiers.</li>
            <li>For the purpose of this policy, sensitive personal data or information has been considered as a part of Personal Information, which may include, but not limited to the following:
              <ul>
                <li>Passwords or authentication information for any of our services or apps.</li>
                <li>Financial information, such as details of bank account, credit card, debit card, or other payment instrument details etc</li>
              </ul>
            </li>
          </ul>
          {/* </p> */}
          <p className='px-8 pt-4 pb-16 w-full mx-auto text-base text-justify tracking-wide'>“Non-Personal Information” which shall mean information that does not identify you or any other individual, and includes session, web beacons and usage and transaction data, aggregate log data and aggregate information. We use this information to inter-alia deliver our web pages to you upon request, to tailor our services to the interests of our users, to measure traffic within our services, to improve the quality, functionality and interactivity and let advertisers know the geographic locations from where our users/ visitors come.</p>
        </div>
      </div>

    </>
  )
}

export default PolicyCE